source "https://github.com/CocoaPods/Specs.git"

platform :ios, "9.0"
inhibit_all_warnings!
use_frameworks! :linkage => :dynamic
install! "cocoapods", :warn_for_unused_master_specs_repo => false

target "MarsDemo" do
  pod "Mars-iOS/Xlog", :path => "../"

  pod "SwiftLint"
  pod "SwiftFormat/CLI"

  target "MarsDemoTests" do
    inherit! :search_paths
  end

  target "MarsDemoUITests" do
    inherit! :search_paths
  end
end
